// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	interview "ai-eino-interview-agent/api/router/interview"
	testRouter "ai-eino-interview-agent/api/router/test"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	interview.Register(r)
	testRouter.Register(r) // 注册测试路由
}
