// Code generated by hertz generator.

package questionbank

import (
	"context"

	questionbank "ai-eino-interview-agent/api/model/questionbank"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetMainCategories .
// @router /api/questionbank/categories/main [GET]
func GetMainCategories(ctx context.Context, c *app.RequestContext) {
	var err error
	var req questionbank.GetMainCategoriesRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(questionbank.GetMainCategoriesResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetSubCategories .
// @router /api/questionbank/categories/sub [GET]
func GetSubCategories(ctx context.Context, c *app.RequestContext) {
	var err error
	var req questionbank.GetSubCategoriesRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(questionbank.GetSubCategoriesResponse)

	c.JSON(consts.StatusOK, resp)
}
