// Code generated by hertz generator.

package questionbank

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _questionbankMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _categoriesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmaincategoriesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsubcategoriesMw() []app.HandlerFunc {
	// your code...
	return nil
}
