// Code generated by hertz generator. DO NOT EDIT.

package interview

import (
	interview "ai-eino-interview-agent/api/handler/interview"
	"github.com/cloudwego/hertz/pkg/app/server"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	{
		_api := root.Group("/api", _apiMw()...)
		{
			_demo := _api.Group("/demo", _demoMw()...)
			{
				_create := _demo.Group("/create", _createMw()...)
				_create.POST("/model", append(_createdemomodelMw(), interview.CreateDemoModel)...)
			}
		}
		{
			_interview := _api.Group("/interview", _interviewMw()...)
			_interview.GET("/answer-record", append(_getanswerrecordMw(), interview.GetAnswerRecord)...)
			_interview.GET("/evaluation", append(_getinterviewevaluationMw(), interview.GetInterviewEvaluation)...)
			_interview.GET("/records", append(_getinterviewrecordsMw(), interview.GetInterviewRecords)...)
			{
				_start := _interview.Group("/start", _startMw()...)
				_start.POST("/stream", append(_startinterviewstreamMw(), interview.StartInterviewStream)...)
			}
			{
				_submit := _interview.Group("/submit", _submitMw()...)
				_submit.POST("/answer", append(_submitinterviewanswerMw(), interview.SubmitInterviewAnswer)...)
			}
		}
		{
			_resume := _api.Group("/resume", _resumeMw()...)
			_resume.GET("/default", append(_getdefaultresumeMw(), interview.GetDefaultResume)...)
			_resume.GET("/list", append(_getuserresumesMw(), interview.GetUserResumes)...)
			_resume.DELETE("/:resume_id", append(_deleteresumeMw(), interview.DeleteResume)...)
			_resume.GET("/:resume_id", append(_getresumeMw(), interview.GetResume)...)
			_resume.PUT("/:resume_id", append(_updateresumeMw(), interview.UpdateResume)...)
			_resume.POST("/set-default", append(_setdefaultresumeMw(), interview.SetDefaultResume)...)
			_resume.POST("/upload", append(_uploadresumeMw(), interview.UploadResume)...)
		}
		{
			_user := _api.Group("/user", _userMw()...)
			_user.POST("/login", append(_loginMw(), interview.Login)...)
			_user.GET("/profile", append(_getprofileMw(), interview.GetProfile)...)
			_user.PUT("/profile", append(_updateprofileMw(), interview.UpdateProfile)...)
			_user.POST("/register", append(_registerMw(), interview.Register)...)
			{
				_create0 := _user.Group("/create", _create0Mw()...)
				_create0.POST("/model", append(_createusermodelMw(), interview.CreateUserModel)...)
			}
			{
				_model := _user.Group("/model", _modelMw()...)
				_model.GET("/check", append(_checkusermodelconfiguredMw(), interview.CheckUserModelConfigured)...)
				_model.GET("/list", append(_listusermodelsMw(), interview.ListUserModels)...)
				{
					_delete := _model.Group("/delete", _deleteMw()...)
					_delete.DELETE("/:id", append(_deleteusermodelMw(), interview.DeleteUserModel)...)
				}
				{
					_details := _model.Group("/details", _detailsMw()...)
					_details.GET("/:id", append(_getusermodelMw(), interview.GetUserModel)...)
				}
				{
					_update := _model.Group("/update", _updateMw()...)
					_update.PUT("/:id", append(_updateusermodelMw(), interview.UpdateUserModel)...)
				}
			}
			{
				_wechat := _user.Group("/wechat", _wechatMw()...)
				_wechat.GET("/callback", append(_wechatcallbackMw(), interview.WechatCallback)...)
				_wechat.GET("/login", append(_wechatloginMw(), interview.WechatLogin)...)
			}
		}
	}
}
