// Code generated by hertz generator.

package interview

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createusermodelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _modelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listusermodelsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteusermodelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _detailsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getusermodelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateusermodelMw() []app.HandlerFunc {
	// your code...
	return nil
}
