// Code generated by thriftgo (0.3.18). DO NOT EDIT.

package interview

import (
	"ai-eino-interview-agent/api/model/interviews"
	titlebank "ai-eino-interview-agent/api/model/titleBank"
	"ai-eino-interview-agent/api/model/user"
	"github.com/apache/thrift/lib/go/thrift"
)

type UserService interface {
	user.UserService
}

type UserServiceClient struct {
	*user.UserServiceClient
}

func NewUserServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *UserServiceClient {
	return &UserServiceClient{
		UserServiceClient: user.NewUserServiceClientFactory(t, f),
	}
}

func NewUserServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *UserServiceClient {
	return &UserServiceClient{
		UserServiceClient: user.NewUserServiceClientProtocol(t, iprot, oprot),
	}
}

func NewUserServiceClient(c thrift.TClient) *UserServiceClient {
	return &UserServiceClient{
		UserServiceClient: user.NewUserServiceClient(c),
	}
}

type InterviewsService interface {
	interviews.InterviewsService
}

type InterviewsServiceClient struct {
	*interviews.InterviewsServiceClient
}

func NewInterviewsServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *InterviewsServiceClient {
	return &InterviewsServiceClient{
		InterviewsServiceClient: interviews.NewInterviewsServiceClientFactory(t, f),
	}
}

func NewInterviewsServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *InterviewsServiceClient {
	return &InterviewsServiceClient{
		InterviewsServiceClient: interviews.NewInterviewsServiceClientProtocol(t, iprot, oprot),
	}
}

func NewInterviewsServiceClient(c thrift.TClient) *InterviewsServiceClient {
	return &InterviewsServiceClient{
		InterviewsServiceClient: interviews.NewInterviewsServiceClient(c),
	}
}

type TitleBankService interface {
	titlebank.TitleBankService
}

type TitleBankServiceClient struct {
	*titlebank.TitleBankServiceClient
}

func NewTitleBankServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *TitleBankServiceClient {
	return &TitleBankServiceClient{
		TitleBankServiceClient: titlebank.NewTitleBankServiceClientFactory(t, f),
	}
}

func NewTitleBankServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *TitleBankServiceClient {
	return &TitleBankServiceClient{
		TitleBankServiceClient: titlebank.NewTitleBankServiceClientProtocol(t, iprot, oprot),
	}
}

func NewTitleBankServiceClient(c thrift.TClient) *TitleBankServiceClient {
	return &TitleBankServiceClient{
		TitleBankServiceClient: titlebank.NewTitleBankServiceClient(c),
	}
}

type UserServiceProcessor struct {
	*user.UserServiceProcessor
}

func NewUserServiceProcessor(handler UserService) *UserServiceProcessor {
	self := &UserServiceProcessor{user.NewUserServiceProcessor(handler)}
	return self
}

type InterviewsServiceProcessor struct {
	*interviews.InterviewsServiceProcessor
}

func NewInterviewsServiceProcessor(handler InterviewsService) *InterviewsServiceProcessor {
	self := &InterviewsServiceProcessor{interviews.NewInterviewsServiceProcessor(handler)}
	return self
}

type TitleBankServiceProcessor struct {
	*titlebank.TitleBankServiceProcessor
}

func NewTitleBankServiceProcessor(handler TitleBankService) *TitleBankServiceProcessor {
	self := &TitleBankServiceProcessor{titlebank.NewTitleBankServiceProcessor(handler)}
	return self
}
