// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package interview

import (
	"ai-eino-interview-agent/api/model/demo"
	"ai-eino-interview-agent/api/model/interviews"
	"ai-eino-interview-agent/api/model/mianshi"
	"ai-eino-interview-agent/api/model/user"
	"github.com/apache/thrift/lib/go/thrift"
)

type UserService interface {
	user.UserService
}

type UserServiceClient struct {
	*user.UserServiceClient
}

func NewUserServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *UserServiceClient {
	return &UserServiceClient{
		UserServiceClient: user.NewUserServiceClientFactory(t, f),
	}
}

func NewUserServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *UserServiceClient {
	return &UserServiceClient{
		UserServiceClient: user.NewUserServiceClientProtocol(t, iprot, oprot),
	}
}

func NewUserServiceClient(c thrift.TClient) *UserServiceClient {
	return &UserServiceClient{
		UserServiceClient: user.NewUserServiceClient(c),
	}
}

type InterviewsService interface {
	interviews.InterviewsService
}

type InterviewsServiceClient struct {
	*interviews.InterviewsServiceClient
}

func NewInterviewsServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *InterviewsServiceClient {
	return &InterviewsServiceClient{
		InterviewsServiceClient: interviews.NewInterviewsServiceClientFactory(t, f),
	}
}

func NewInterviewsServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *InterviewsServiceClient {
	return &InterviewsServiceClient{
		InterviewsServiceClient: interviews.NewInterviewsServiceClientProtocol(t, iprot, oprot),
	}
}

func NewInterviewsServiceClient(c thrift.TClient) *InterviewsServiceClient {
	return &InterviewsServiceClient{
		InterviewsServiceClient: interviews.NewInterviewsServiceClient(c),
	}
}

type DemoService interface {
	demo.DemoService
}

type DemoServiceClient struct {
	*demo.DemoServiceClient
}

func NewDemoServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *DemoServiceClient {
	return &DemoServiceClient{
		DemoServiceClient: demo.NewDemoServiceClientFactory(t, f),
	}
}

func NewDemoServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *DemoServiceClient {
	return &DemoServiceClient{
		DemoServiceClient: demo.NewDemoServiceClientProtocol(t, iprot, oprot),
	}
}

func NewDemoServiceClient(c thrift.TClient) *DemoServiceClient {
	return &DemoServiceClient{
		DemoServiceClient: demo.NewDemoServiceClient(c),
	}
}

type MianshiService interface {
	mianshi.MianshiService
}

type MianshiServiceClient struct {
	*mianshi.MianshiServiceClient
}

func NewMianshiServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *MianshiServiceClient {
	return &MianshiServiceClient{
		MianshiServiceClient: mianshi.NewMianshiServiceClientFactory(t, f),
	}
}

func NewMianshiServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *MianshiServiceClient {
	return &MianshiServiceClient{
		MianshiServiceClient: mianshi.NewMianshiServiceClientProtocol(t, iprot, oprot),
	}
}

func NewMianshiServiceClient(c thrift.TClient) *MianshiServiceClient {
	return &MianshiServiceClient{
		MianshiServiceClient: mianshi.NewMianshiServiceClient(c),
	}
}

type UserServiceProcessor struct {
	*user.UserServiceProcessor
}

func NewUserServiceProcessor(handler UserService) *UserServiceProcessor {
	self := &UserServiceProcessor{user.NewUserServiceProcessor(handler)}
	return self
}

type InterviewsServiceProcessor struct {
	*interviews.InterviewsServiceProcessor
}

func NewInterviewsServiceProcessor(handler InterviewsService) *InterviewsServiceProcessor {
	self := &InterviewsServiceProcessor{interviews.NewInterviewsServiceProcessor(handler)}
	return self
}

type DemoServiceProcessor struct {
	*demo.DemoServiceProcessor
}

func NewDemoServiceProcessor(handler DemoService) *DemoServiceProcessor {
	self := &DemoServiceProcessor{demo.NewDemoServiceProcessor(handler)}
	return self
}

type MianshiServiceProcessor struct {
	*mianshi.MianshiServiceProcessor
}

func NewMianshiServiceProcessor(handler MianshiService) *MianshiServiceProcessor {
	self := &MianshiServiceProcessor{mianshi.NewMianshiServiceProcessor(handler)}
	return self
}
