// Code generated by hertz generator.

package interview

import (
	"ai-eino-interview-agent/api/response"
	"context"

	demo "ai-eino-interview-agent/api/model/demo"
	demoservice "ai-eino-interview-agent/internal/service/demo"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreateDemo .
// @router /api/demo/create [POST]
func CreateDemo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req demo.CreateDemoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	_, err = demoservice.NewDemoService().Create(ctx, req)
	if err != nil {
		return
	}
	resp := new(demo.CreateDemoResponse)

	response.Success(ctx, c, resp)
}
