// Code generated by hertz generator.

package interview

import (
	"context"

	titleBank "ai-eino-interview-agent/api/model/titleBank"
	titleBankService "ai-eino-interview-agent/internal/service/titleBank"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreateInterviewTitle .
// @router /api/titleBank/create/title [POST]
func CreateInterviewTitle(ctx context.Context, c *app.RequestContext) {
	var err error
	var req titleBank.CreateInterviewTitleRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	manager := titleBankService.NewTitleBankManager()
	resp, err := manager.CreateInterviewTitle(ctx, req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// CreateInterviewLabel .
// @router /api/titleBank/create/label [POST]
func CreateInterviewLabel(ctx context.Context, c *app.RequestContext) {
	var err error
	var req titleBank.CreateInterviewLabelRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	manager := titleBankService.NewTitleBankManager()
	resp, err := manager.CreateInterviewLabel(ctx, req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// CreateInterviewParse .
// @router /api/titleBank/create/parse [POST]
func CreateInterviewParse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req titleBank.CreateInterviewParseRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	manager := titleBankService.NewTitleBankManager()
	resp, err := manager.CreateInterviewParse(ctx, req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// CreateUserTitleInteract .
// @router /api/titleBank/create/interact [POST]
func CreateUserTitleInteract(ctx context.Context, c *app.RequestContext) {
	var err error
	var req titleBank.CreateUserTitleInteractRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	manager := titleBankService.NewTitleBankManager()
	resp, err := manager.CreateUserTitleInteract(ctx, req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
