// Code generated by hertz generator.

package interview

import (
	"context"

	titleBank "ai-eino-interview-agent/api/model/titleBank"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreateInterviewTitle .
// @router /api/titleBank/create/title [POST]
func CreateInterviewTitle(ctx context.Context, c *app.RequestContext) {
	var err error
	var req titleBank.CreateInterviewTitleRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(titleBank.CreateInterviewTitleResponse)

	c.JSON(consts.StatusOK, resp)
}

// CreateInterviewLabel .
// @router /api/titleBank/create/label [POST]
func CreateInterviewLabel(ctx context.Context, c *app.RequestContext) {
	var err error
	var req titleBank.CreateInterviewLabelRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(titleBank.CreateInterviewLabelResponse)

	c.JSON(consts.StatusOK, resp)
}

// CreateInterviewParse .
// @router /api/titleBank/create/parse [POST]
func CreateInterviewParse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req titleBank.CreateUserTitleInteractRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(titleBank.CreateInterviewParseResponse)

	c.JSON(consts.StatusOK, resp)
}

// CreateUserTitleInteract .
// @router /api/titleBank/create/interact [POST]
func CreateUserTitleInteract(ctx context.Context, c *app.RequestContext) {
	var err error
	var req titleBank.CreateUserTitleInteractResponse
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(titleBank.CreateInterviewLabelResponse)

	c.JSON(consts.StatusOK, resp)
}
