// Code generated by hertz generator.

package interview

import (
	"context"
	"errors"

	user "ai-eino-interview-agent/api/model/user"
	"ai-eino-interview-agent/internal/middleware"
	userservice "ai-eino-interview-agent/internal/service/user"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"gorm.io/gorm"
)

// CreateUserModel .
// @router /api/user/create/model [POST]
func CreateUserModel(ctx context.Context, c *app.RequestContext) {
	var req user.CreateUserModelRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		c.String(consts.StatusUnauthorized, "unauthorized")
		return
	}

	state, err := userservice.NewModelManager().CreateUserModel(ctx, int64(userID), req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := user.NewCreateUserModelResponse()
	resp.State = state
	c.JSON(consts.StatusOK, resp)
}

// ListUserModels .
// @router /api/user/model/list [GET]
func ListUserModels(ctx context.Context, c *app.RequestContext) {
	var req user.ListUserModelsRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		c.String(consts.StatusUnauthorized, "unauthorized")
		return
	}

	page := req.GetPage()
	if page <= 0 {
		page = 1
	}
	size := req.GetSize()
	if size <= 0 {
		size = 10
	}
	if size > 100 {
		size = 100
	}

	models, total, err := userservice.NewModelManager().ListUserModels(ctx, int64(userID), req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := user.NewListUserModelsResponse()
	resp.List = make([]*user.UserModelItem, 0, len(models))
	for _, m := range models {
		resp.List = append(resp.List, userservice.ToUserModelItem(m))
	}
	resp.Total = total
	resp.Page = page
	resp.Size = size

	c.JSON(consts.StatusOK, resp)
}

// GetUserModel .
// @router /api/user/model/details/:id [GET]
func GetUserModel(ctx context.Context, c *app.RequestContext) {
	var req user.IDRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		c.String(consts.StatusUnauthorized, "unauthorized")
		return
	}

	record, err := userservice.NewModelManager().UserModelDetail(ctx, int64(userID), req.GetID())
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			c.String(consts.StatusNotFound, "user model not found")
			return
		}
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := user.NewGetUserModelResponse()
	resp.Data = userservice.ToUserModelDetail(record)

	c.JSON(consts.StatusOK, resp)
}

// UpdateUserModel .
// @router /api/user/model/update/:id [PUT]
func UpdateUserModel(ctx context.Context, c *app.RequestContext) {
	var req user.UpdateUserModelRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		c.String(consts.StatusUnauthorized, "unauthorized")
		return
	}

	if err := userservice.NewModelManager().UpdateUserModel(ctx, int64(userID), req); err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			c.String(consts.StatusNotFound, "user model not found")
			return
		}
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := user.NewUpdateUserModelResponse()
	c.JSON(consts.StatusOK, resp)
}

// DeleteUserModel .
// @router /api/user/model/delete/:id [DELETE]
func DeleteUserModel(ctx context.Context, c *app.RequestContext) {
	var req user.IDRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		c.String(consts.StatusUnauthorized, "unauthorized")
		return
	}

	if err := userservice.NewModelManager().DeleteUserModel(ctx, int64(userID), req.GetID()); err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			c.String(consts.StatusNotFound, "user model not found")
			return
		}
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := user.NewDeleteUserModelResponse()
	c.JSON(consts.StatusOK, resp)
}

// Register .
// @router /api/user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	manager := userservice.NewUserManager()
	resp, err := manager.Register(ctx, req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// Login .
// @router /api/user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	manager := userservice.NewUserManager()
	resp, err := manager.Login(ctx, req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// GetProfile .
// @router /api/user/profile [GET]
func GetProfile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.EmptyRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		c.String(consts.StatusUnauthorized, "unauthorized")
		return
	}

	manager := userservice.NewUserManager()
	profile, err := manager.GetProfile(ctx, uint(userID))
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := new(user.GetProfileResponse)
	resp.Data = profile

	c.JSON(consts.StatusOK, resp)
}

// UpdateProfile .
// @router /api/user/profile [PUT]
func UpdateProfile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UpdateProfileRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		c.String(consts.StatusUnauthorized, "unauthorized")
		return
	}

	manager := userservice.NewUserManager()
	profile, err := manager.UpdateProfile(ctx, userID, req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := new(user.UpdateProfileResponse)
	resp.Data = profile

	c.JSON(consts.StatusOK, resp)
}

// Logout .
// @router /api/user/logout [POST]
func Logout(ctx context.Context, c *app.RequestContext) {
	userID := middleware.GetUserID(c)
	data := map[string]interface{}{
		"status": "logged_out",
	}
	if userID != 0 {
		data["user_id"] = userID
	}
	c.JSON(consts.StatusOK, map[string]interface{}{
		"code":    0,
		"message": "ok",
		"data":    data,
	})
}

// WechatLogin .
// @router /api/user/wechat/login [GET]
func WechatLogin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.EmptyRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	manager := userservice.NewUserManager()
	resp, err := manager.WechatLogin(ctx)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// WechatCallback .
// @router /api/user/wechat/callback [GET]
func WechatCallback(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.WechatCallbackRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	manager := userservice.NewUserManager()
	resp, err := manager.WechatCallback(ctx, req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
