// Code generated by hertz generator.

package interview

import (
	userservice "ai-eino-interview-agent/internal/service/user"
	"context"

	user "ai-eino-interview-agent/api/model/user"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreateUserModel .
// @router /api/user/create/model [POST]
func CreateUserModel(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.CreateUserModelRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	userId := int64(11111)
	res, err := userservice.NewModelManager().CreateUserModel(ctx, userId, req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	resp := new(user.CreateUserModelResponse)
	resp.State = res
	c.JSON(consts.StatusOK, resp)
}

// ListUserModels .
// @router /api/user/model/list [GET]
func ListUserModels(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.ListUserModelsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	userId := int64(11111)
	res, totl, err := userservice.NewModelManager().ListUserModels(ctx, userId, req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	resp := new(user.ListUserModelsResponse)
	resp.Total = totl
	modelList := make([]*user.UserModelItem, 0)
	for _, model := range res {
		modelList = append(modelList, &user.UserModelItem{
			ID:            int64(model.ID),
			Name:          model.Name,
			ModelKey:      model.ModelKey,
			Protocol:      model.Protocol,
			BaseURL:       model.BaseURL,
			ProviderName:  model.ProviderName,
			MetaID:        &model.MetaID,
			DefaultParams: &model.DefaultParams,
			ConfigJSON:    &model.ConfigJSON,
			Scope:         int32(model.Scope),
			Status:        int32(model.Status),
			CreatedAt:     model.CreatedAt,
			UpdatedAt:     model.UpdatedAt,
		})
	}
	resp.List = modelList

	c.JSON(consts.StatusOK, resp)
}

// GetUserModel .
// @router /api/user/model/details/:id [GET]
func GetUserModel(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.IDRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	userId := int64(11111)
	res, err := userservice.NewModelManager().UserModelDetail(ctx, userId, req.ID)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	resp := new(user.GetUserModelResponse)
	resp.Data = &user.UserModelDetail{
		ID:            int64(res.ID),
		Name:          res.Name,
		ModelKey:      res.ModelKey,
		Protocol:      res.Protocol,
		BaseURL:       res.BaseURL,
		ProviderName:  res.ProviderName,
		MetaID:        &res.MetaID,
		DefaultParams: &res.DefaultParams,
		ConfigJSON:    &res.ConfigJSON,
		Scope:         int32(res.Scope),
	}
	c.JSON(consts.StatusOK, resp)
}

// UpdateUserModel .
// @router /api/user/model/update/:id [PUT]
func UpdateUserModel(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UpdateUserModelRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.UpdateUserModelResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteUserModel .
// @router /api/user/model/delete/:id [DELETE]
func DeleteUserModel(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.IDRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.DeleteUserModelResponse)

	c.JSON(consts.StatusOK, resp)
}
